from __future__ import annotations

from collections.abc import Mapping
from threading import RLock

_LOCK = RLock()
_SNAPSHOT: dict[str, str] = {}

RUNTIME_SIGNALS_DISABLED = "SARI_DAEMON_SIGNALS_DISABLED"
RUNTIME_SHUTDOWN_INTENT = "SARI_DAEMON_SHUTDOWN_INTENT"
RUNTIME_SUICIDE_STATE = "SARI_DAEMON_SUICIDE_STATE"
RUNTIME_ACTIVE_LEASES_COUNT = "SARI_DAEMON_ACTIVE_LEASES_COUNT"
RUNTIME_LEASES = "SARI_DAEMON_LEASES"
RUNTIME_LAST_REAP_AT = "SARI_DAEMON_LAST_REAP_AT"
RUNTIME_REAPER_LAST_RUN_AT = "SARI_DAEMON_REAPER_LAST_RUN_AT"
RUNTIME_NO_CLIENT_SINCE = "SARI_DAEMON_NO_CLIENT_SINCE"
RUNTIME_GRACE_REMAINING = "SARI_DAEMON_GRACE_REMAINING"
RUNTIME_GRACE_REMAINING_MS = "SARI_DAEMON_GRACE_REMAINING_MS"
RUNTIME_SHUTDOWN_ONCE_SET = "SARI_DAEMON_SHUTDOWN_ONCE_SET"
RUNTIME_LAST_EVENT_TS = "SARI_DAEMON_LAST_EVENT_TS"
RUNTIME_EVENT_QUEUE_DEPTH = "SARI_DAEMON_EVENT_QUEUE_DEPTH"
RUNTIME_LAST_SHUTDOWN_REASON = "SARI_DAEMON_LAST_SHUTDOWN_REASON"
RUNTIME_SHUTDOWN_REASON = "SARI_DAEMON_SHUTDOWN_REASON"
RUNTIME_WORKERS_ALIVE = "SARI_DAEMON_WORKERS_ALIVE"


def publish_daemon_runtime_state(values: Mapping[str, object]) -> None:
    data = {str(k): str(v) for k, v in values.items()}
    with _LOCK:
        _SNAPSHOT.clear()
        _SNAPSHOT.update(data)


def get_daemon_runtime_state_snapshot() -> dict[str, str]:
    with _LOCK:
        return dict(_SNAPSHOT)


def clear_daemon_runtime_state() -> None:
    with _LOCK:
        _SNAPSHOT.clear()
